import turtle
t = turtle.Turtle()
s = turtle.Screen()
t.speed(0)
s.setup(800, 500)
t.pensize(12)
t.pencolor("black")
t.circle(80)
t.penup()
t.goto(-200, 0)
t.pendown()
t.pencolor("blue")
t.circle(80)
t.penup()
t.goto(200, 0)
t.pendown()
t.pencolor("red")
t.circle(80)
t.penup()
t.goto(-100, -100)
t.pendown()
t.pencolor("yellow")
t.circle(80)
t.penup()
t.goto(100, -100)
t.pendown()
t.pencolor("green")
t.circle(80)
t.hideturtle()
turtle.done()